# backend/agents/ethics_agent.py
"""EthicsAgent — pure Python transparency notes, bias statements, and disclaimers."""
from __future__ import annotations


_MAKE_BIAS_NOTES: dict[str, str] = {
    "tesla":     "EV market data is sparse pre-2020; EV-specific subsidies may affect residual values.",
    "ford":      "Truck segment pricing is highly regional; national averages may not reflect your local market.",
    "chevrolet": "Truck segment pricing is highly regional; national averages may not reflect your local market.",
    "gmc":       "Truck segment pricing is highly regional; national averages may not reflect your local market.",
    "ram":       "Truck segment pricing is highly regional; national averages may not reflect your local market.",
    "jeep":      "Off-road/adventure segments show high regional price variance not fully captured by this model.",
    "bmw":       "Luxury vehicle data is underrepresented; maintenance cost risk is not factored into pricing.",
    "mercedes":  "Luxury vehicle data is underrepresented; maintenance cost risk is not factored into pricing.",
    "audi":      "Luxury vehicle data is underrepresented; maintenance cost risk is not factored into pricing.",
    "porsche":   "Performance/luxury segments show high variance; this model was trained primarily on mass-market data.",
}

_DEFAULT_BIAS_NOTE = (
    "This model was trained primarily on US mass-market vehicles (2010–2022). "
    "Predictions for niche, luxury, or very new/old vehicles carry higher uncertainty."
)

_ETHICS_DISCLAIMER = (
    "CarIntel provides data-driven price intelligence for informational purposes only. "
    "Recommendations are generated by machine learning models and AI analysis — not human financial advice. "
    "Always verify with a licensed dealer or independent inspection before purchasing."
)


def run(
    make: str,
    model: str,
    year: int,
    forecast_method: str,
    confidence_score: int,
    volatility_index: str,
    has_price_history: bool,
    inventory_trend: str,
) -> dict:
    """Generate transparency note, bias statement, and ethics disclaimer.

    Returns
    -------
    {
        "transparency_note": str,
        "bias_statement": str,
        "ethics_disclaimer": str,
        "agent_log_entry": {...},
    }
    """
    # ── Transparency note (method + data quality) ─────────────────────────────
    _method_labels = {
        "prophet":          "Facebook Prophet time-series model (3+ months of price history)",
        "llm_blended":      "XGBoost + GPT-4o-mini blended forecast (statistical + AI reasoning)",
        "linear":           "linear extrapolation (limited 1–2 months of data)",
        "statistical":      "statistical model with blended AI analysis",
        "market_avg":       "market-wide average trend (no vehicle-specific history available)",
        "industry_default": "US industry default averages (no local market data in database)",
    }
    method_desc = _method_labels.get(forecast_method, f"'{forecast_method}' forecast method")

    data_quality = "high" if has_price_history else "moderate"
    inv_note = "" if inventory_trend != "unknown" else " Inventory data unavailable for this market."

    transparency = (
        f"Forecast generated using {method_desc}. "
        f"Data quality: {data_quality}.{inv_note} "
        f"Confidence score: {confidence_score}% | Volatility: {volatility_index}."
    )

    # ── Bias statement (make-specific or default) ─────────────────────────────
    bias = _MAKE_BIAS_NOTES.get(make.lower(), _DEFAULT_BIAS_NOTE)

    # Low confidence or high volatility → additional caveat
    if confidence_score < 65 or volatility_index == "High":
        bias += (
            " Due to lower confidence or high market volatility, "
            "treat this prediction with additional caution."
        )

    msg = f"Transparency and ethics review complete. Confidence: {confidence_score}%. Volatility: {volatility_index}."

    return {
        "transparency_note": transparency,
        "bias_statement":    bias,
        "ethics_disclaimer": _ETHICS_DISCLAIMER,
        "agent_log_entry": {
            "agent":   "EthicsAgent",
            "status":  "ok",
            "message": msg,
            "output": {
                "transparency_note": transparency,
                "bias_statement":    bias,
            },
        },
    }
